inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - 'vendor/**/*'
    - 'vender/**/*'
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'node_modules/**/*'
    # rspecは未完成なので一旦除外。完成したら外すこと。
    - 'spec/**/*'

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# AbcSizeを30まで許可
# 数値は要検討
Metrics/AbcSize:
  Max: 30

# メソッドの長さを20行まで許可
# 数値は要検討
Metrics/MethodLength:
  Max: 20