default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: chiuney6
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: listing_development

test:
  <<: *default
  database: listing_test

production:
  <<: *default
  database: listing_production
  username: chiuney6
  password: <%= ENV['DATABASE_PASSWORD'] %>