default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: listing_development

test:
  <<: *default
  database: listing_test

production:
  <<: *default
  database: listing_production
  url: <%= ENV['DATABASE_URL'] %>